[package]
name = "sfml-xt"
version = "0.1.0"
edition = "2021"
description = "Various extensions to SFML's core functionality"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.20.0"
